FROM python:3.12.3-slim

WORKDIR /app

COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt 

COPY api.py .
COPY model ./model 

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "api:app"]

